### ISSUE TITLE
No data for automatic tests session recording

### ISSUE THREAD

**Issue by marcinogo** [Drill4J/Drill4J#238]
I want to try *Drill4J* with *PetClinic* application, but *Drill4J* could not record information about autotests.

* I installed *Drill4J Admin* with command `docker-compose up -d`.
* I stared appliaction with command `java -agentpath:"../linuxX64-0.5.0/libdrill_agent.so=drillInstallationDir=../linuxX64-0.5.0,adminAddress=localhost:8090,agentId=test-agent,buildVersion=0.0.1" -jar target/*.jar`. 
* Agent was properly registred in *Drill4J Admin*.
* I added *Maven* plugin for *Drill4J* as shown [in instruction](https://drill4j.github.io/autotest-agent-guide/).
* I changed `<agentId>` in plugin configuration to `<agentId>test-agent</agentId>`.

In the separate terminal, I run the command `mvn test` to register autotests.
Yet when I try it I get message: `No data for session f44df379-5160-4a9d-b127-df73d35a935a`. Of course, session-id vary from run to run.

What is the problem here? What data from tests are necessary to register them?

My *Maven* configuration:
![Screenshot from 2020-07-09 09-27-47](https://user-images.githubusercontent.com/27285215/87010524-f5d0ab00-c1c6-11ea-89c7-87a3b1882ce5.png)
![Screenshot from 2020-07-09 09-27-57](https://user-images.githubusercontent.com/27285215/87010533-f8cb9b80-c1c6-11ea-8480-42000078ede6.png)

Output during and after tests:
![Screenshot from 2020-07-09 09-30-20](https://user-images.githubusercontent.com/27285215/87010612-1bf64b00-c1c7-11ea-8b2b-c31078ed3ddd.png)
![Screenshot from 2020-07-09 09-30-58](https://user-images.githubusercontent.com/27285215/87010619-1d277800-c1c7-11ea-94f8-e76372878b72.png)

**Comment by Adenmin** [comment]
Hi!
Could you please write more info about autotests? 
Test runner, UI or API, tools? Or if you have a repo with these tests on GitHub then give a link.
Thanks!

**Comment by marcinogo** [comment]
Everything that is included in https://github.com/spring-projects/spring-petclinic
I didn't add or change any test, source code or `pom.xml` configuration apart from *Drill4J* plugin config.

**Comment by Adenmin** [comment]
Drill coverage tracking based on injecting HTTP headers into test request/response.
In petclinic tests of this repo https://github.com/spring-projects/spring-petclinic  I see only tests without interaction with HTTP 
 and unfortunately, Drill hasn't supported this type of autotests yet.

If you want to try autotest and Drill, you can write some simple test by http://rest-assured.io/ for petclinic
or try manual tests by Drill browser extension.

**Comment by marcinogo** [comment]
Ok I understand now what was the problem. Thank you for your help.
